import {PlayerInputType} from '../input/PlayerInputType';
import {CardModel} from './CardModel';
import {ColonyModel} from './ColonyModel';
import {PayProductionModel} from './PayProductionUnitsModel';
import {AresData} from '../ares/AresData';
import {Message} from '../logs/Message';
import {PartyName} from '../turmoil/PartyName';
import {TurmoilModel} from './TurmoilModel';
import {StaticGlobalEventProperties} from '../../server/turmoil/globalEvents/GlobalEvent';
import {PlayerId, SpaceId} from '../Types';
import {Color} from '../Color';

export interface PlayerInputModel {
    id: string | undefined;
    amount: number | undefined;
    availableSpaces: Array<SpaceId> | undefined;
    canUseHeat: boolean | undefined;
    canUseSteel: boolean | undefined;
    canUseTitanium: boolean | undefined;
    canUseSeeds: boolean | undefined;
    canUseData: boolean | undefined;
    canUseLunaTradeFederationTitanium: boolean | undefined;
    cards: Array<CardModel> | undefined;
    inputType: PlayerInputType;
    options: Array<PlayerInputModel> | undefined;
    min: number | undefined;
    max: number | undefined;
    maxByDefault?: boolean;
    microbes: number | undefined;
    floaters: number | undefined;
    science: number | undefined;
    seeds: number | undefined;
    data: number | undefined;
    players: Array<PlayerId | Color | 'NEUTRAL'> | undefined;
    title: string | Message;
    buttonLabel: string;
    coloniesModel : Array<ColonyModel> | undefined;
    payProduction?: PayProductionModel;
    aresData?: AresData;
    selectBlueCardAction: boolean;
    showOnlyInLearnerMode?: boolean;
    showOwner?: boolean;
    availableParties: Array<PartyName> | undefined;
    turmoil?: TurmoilModel;
    globalEventCards?:Array<StaticGlobalEventProperties>;
}
