export enum GameModule {
    Override = 'invalid',
    Base = 'base',
    CorpEra = 'corpera',
    Promo = 'promo',
    Venus = 'venus',
    Colonies = 'colonies',
    Prelude = 'prelude',
    Turmoil = 'turmoil',
    Breakthrough = 'breakthrough',
    Community = 'community',
    Eros = 'eros',
    Ares = 'ares',
    Moon = 'moon',
}
